---
- name: Install NeoVim build dependecies
  become: true
  ansible.builtin.apt:
    pkg:
      - ninja-build
      - gettext
      - cmake
      - unzip
- name: Clone NeoVim repo
  git:
    repo: "https://github.com/neovim/neovim"
    dest: "$HOME/.neovim/"
- name: Build NeoVim
  ansible.builtin.shell:
    cmd: |
      cd $HOME/.neovim/
      rm -rf build
      make distclean
      make CMAKE_BUILD_TYPE=Release
- name: Install NeoVim
  become: true
  ansible.builtin.shell:
    cmd: |
      cd $HOME/.neovim/
      make CMAKE_INSTALL_PREFIX=$HOME/.local install
