---
- include_tasks: reusable_link_all_files.yml
  vars:
    - src: "~/dotfiles/config/kitty/"
    - dest: "~/.config/kitty/"
- include_tasks: reusable_link_all_files.yml
  vars:
    - src: "~/dotfiles/config/fish/"
    - dest: "~/.config/fish/"
- name: Link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    state: link
  loop:
    - {
        src: "~/dotfiles/config/starship.toml",
        dest: "~/.config/starship.toml",
      }
    - { src: "~/dotfiles/.gitconfig", dest: "~/.gitconfig" }
- name: Clone NeoVim config
  git:
    repo: "https://github.com/pmizio/reactive.nvim"
    dest: "~/.config/nvim/"
