---
- name: Get all config files from {{src}}
  find:
    paths: "{{src}}"
    file_type: "any"
    patterns: "*"
  register: files
- name: Link files to {{dest}}
  file:
    src: "{{item.path}}"
    dest: "{{dest}}{{item.path | basename}}"
    force: true
    state: link
  with_items: "{{files.files}}"
